### ISSUE TITLE
Vehicle test drive timer within 30 seconds

### ISSUE THREAD

**Issue by Doxy4** [qbcore-framework/qb-vehicleshop#211] opened 2022-06-16 18:50 UTC
If you test drive a car it gets the 30  second timer, if you return the car and go test drive a new car within the 30 seconds the car will be deleted because the timer dose not reset for every car you test drive.

**Comment by GhzGarage** [comment] 2022-07-13 05:20
I just pushed a fix for this if the issue is still effecting you. Thanks for the report

**Closed by GhzGarage** 2022-07-13 05:20 UTC
Labels: bug
